/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "student.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

StudentResponse *
add_student_1(Student *argp, CLIENT *clnt)
{
	static StudentResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADD_STUDENT,
		(xdrproc_t) xdr_Student, (caddr_t) argp,
		(xdrproc_t) xdr_StudentResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

StudentResponse *
search_student_1(StudentRequest *argp, CLIENT *clnt)
{
	static StudentResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SEARCH_STUDENT,
		(xdrproc_t) xdr_StudentRequest, (caddr_t) argp,
		(xdrproc_t) xdr_StudentResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

StudentResponse *
update_student_1(Student *argp, CLIENT *clnt)
{
	static StudentResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, UPDATE_STUDENT,
		(xdrproc_t) xdr_Student, (caddr_t) argp,
		(xdrproc_t) xdr_StudentResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

StudentResponse *
delete_student_1(StudentRequest *argp, CLIENT *clnt)
{
	static StudentResponse clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DELETE_STUDENT,
		(xdrproc_t) xdr_StudentRequest, (caddr_t) argp,
		(xdrproc_t) xdr_StudentResponse, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
