/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "student.h"

bool_t
xdr_Student (XDR *xdrs, Student *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->department, 50))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->cgpa))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_StudentRequest (XDR *xdrs, StudentRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_StudentResponse (XDR *xdrs, StudentResponse *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->success))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->message, 100))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->student_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->student_name, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->student_department, 50))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->student_cgpa))
		 return FALSE;
	return TRUE;
}
