/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STUDENT_H_RPCGEN
#define _STUDENT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Student {
	int id;
	char *name;
	char *department;
	float cgpa;
};
typedef struct Student Student;

struct StudentRequest {
	int id;
};
typedef struct StudentRequest StudentRequest;

struct StudentResponse {
	int success;
	char *message;
	int student_id;
	char *student_name;
	char *student_department;
	float student_cgpa;
};
typedef struct StudentResponse StudentResponse;

#define STUDENT_DATABASE 0x20000001
#define STUDENT_DATABASE_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD_STUDENT 1
extern  StudentResponse * add_student_1(Student *, CLIENT *);
extern  StudentResponse * add_student_1_svc(Student *, struct svc_req *);
#define SEARCH_STUDENT 2
extern  StudentResponse * search_student_1(StudentRequest *, CLIENT *);
extern  StudentResponse * search_student_1_svc(StudentRequest *, struct svc_req *);
#define UPDATE_STUDENT 3
extern  StudentResponse * update_student_1(Student *, CLIENT *);
extern  StudentResponse * update_student_1_svc(Student *, struct svc_req *);
#define DELETE_STUDENT 4
extern  StudentResponse * delete_student_1(StudentRequest *, CLIENT *);
extern  StudentResponse * delete_student_1_svc(StudentRequest *, struct svc_req *);
extern int student_database_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD_STUDENT 1
extern  StudentResponse * add_student_1();
extern  StudentResponse * add_student_1_svc();
#define SEARCH_STUDENT 2
extern  StudentResponse * search_student_1();
extern  StudentResponse * search_student_1_svc();
#define UPDATE_STUDENT 3
extern  StudentResponse * update_student_1();
extern  StudentResponse * update_student_1_svc();
#define DELETE_STUDENT 4
extern  StudentResponse * delete_student_1();
extern  StudentResponse * delete_student_1_svc();
extern int student_database_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Student (XDR *, Student*);
extern  bool_t xdr_StudentRequest (XDR *, StudentRequest*);
extern  bool_t xdr_StudentResponse (XDR *, StudentResponse*);

#else /* K&R C */
extern bool_t xdr_Student ();
extern bool_t xdr_StudentRequest ();
extern bool_t xdr_StudentResponse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STUDENT_H_RPCGEN */
